### ISSUE TITLE
Add sanity tests to CI

### ISSUE THREAD

**Issue by rhysmeister** [ansible-collections/community.elastic#30]
##### SUMMARY
Add sanity tests to CI.

##### ISSUE TYPE
- Feature Idea

**Comment by gundalow** [comment]
You have `sanity` in https://github.com/ansible-collections/community.elastic/blob/master/.github/workflows/ansible-test.yml#L8-L33 already

What version(s) of Python does this collection support? If Python 2+ and Python3+, then just remove the `--python 3.6` from https://github.com/ansible-collections/community.elastic/blob/master/.github/workflows/ansible-test.yml#L33

**Comment by rhysmeister** [comment]
Yep, not sure how I missed that. The --python 3.6 is a hangover from when you provided the initial version of  this file for the mongodb repo. If I recall correctly other python versions had issues.
