### ISSUE TITLE
ansible-doc community.elastic.elastic_role example word "indicies" error, should be indices

### ISSUE THREAD

**Issue by xiaobao623** [ansible-collections/community.elastic#99]
Role doc EXAMPLES:

- name: Create a role called admin
  community.elastic.elastic_role:
    name: admin
    cluster:
      - all
    **_indicies_**:
      names:
       - index1
       - index2
       - index3
      privileges:
       - all

the example indicies should be indices

=====Task run test======

TASK [create new role bsg] *************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "
Unsupported parameters for (community.elastic.elastic_role) module: **_indicies_**. 
Supported parameters include: applications, auth_method, auth_scheme, cafile, cluster, connection_options, global_v, **indices**, login_hosts, login_password, login_port, login_user, metadata, name, run_as, state, timeout."}

**Comment by rhysmeister** [comment]
Corrected in https://github.com/ansible-collections/community.elastic/pull/100
